http://mangione.page/* https://alejandro.mangione.page/:splat 301!
https://mangione.page/* https://alejandro.mangione.page/:splat 301!

http://www.mangione.page/* https://alejandro.mangione.page/:splat 301!
https://www.mangione.page/* https://alejandro.mangione.page/:splat 301!